### ISSUE TITLE
Code generation and need for discriminator

### ISSUE THREAD

**Issue by kwalcock** [ml4ai/automates-v2#36]
Java/Scala code generation doesn't work from files like `gromet_FN_v0.1.4.yaml` and `gromet_metadata_v0.1.4.yaml` for lack of a discriminator in superclasses.  For example,

```yaml
    GrometObject:
      description: Generic base class for any GroMEt object
      type: object
      properties:
        metadata:
          description: Index (integer) into the metadata_collection table in GrometFNModule.
          type: integer
# Lines like the ones below need to be added     
        gromet_object_type: # added
          type: string #
      discriminator: # added
        propertyName: gromet_object_type
```
When subclass objects are written out, a field should then appear as such:
```json
{
    "gromet_object_type": "GrometFNModule",
    "schema": "FN",
    "schema_version": "0.1.4",

```

This allows the generated Java/Scala code to figure out how to deserialize the object.

I don't (yet) know how the Python code is working without this, but will probably notice soon.  I am hand editing the files like `cond1--Gromet-FN-auto.json` to add this information to make sure the updates to the yaml file that I'm about to suggest work.

Perhaps this issue has been encountered before, so I'm filing this slightly prematurely in case there's more I should know before continuing.
